name: Fraud Batch Pipeline

on:
  # 1. Manual runs
  workflow_dispatch:

  # 2. Periodic runs (every 15 minutes for demo, adjust as needed)
  schedule:
    - cron: "*/15 * * * *"

  # 3. Instant runs triggered by FastAPI (via GitHub API)
  repository_dispatch:
    types: [fraud-run]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          NEON_CONN: ${{ secrets.NEON_CONN }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python pipeline.py
