name: Run Fraud Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          NEON_CONN: ${{ secrets.NEON_CONN }}
        run: python pipeline.py
